options {
    directory "/var/cache/bind";
    allow-query { any; };
    listen-on { any; };
};

zone "mysite.local" {
    type slave;
    file "/var/cache/bind/slaves/mysite.local.raw";
    masters { 172.20.0.200; }; # آی‌پی سرور Master
};

