options {
    directory "/var/cache/bind";
    allow-query { any; };
    listen-on { any; };
};

zone "mysite.local" {
    type master;
    file "/etc/bind/mysite.local.zone";
    allow-transfer { 172.20.0.201; }; 
    also-notify { 172.20.0.201; };     
};
